export const KEYBOARDS = [
  { id: 1, type: "delete", value: "C" },
  { id: 2, type: "calculator", value: "%" },
  { id: 3, type: "calculator", value: "/" },
  { id: 4, type: "calculator", value: "x" },
  { id: 5, type: "number", value: "1" },
  { id: 6, type: "number", value: "2" },
  { id: 7, type: "number", value: "3" },
  { id: 8, type: "calculator", value: "+" },
  { id: 9, type: "number", value: "4" },
  { id: 10, type: "number", value: "5" },
  { id: 11, type: "number", value: "6" },
  { id: 12, type: "calculator", value: "-" },
  { id: 13, type: "number", value: "7" },
  { id: 14, type: "number", value: "8" },
  { id: 15, type: "number", value: "9" },
  { id: 16, type: "number", value: "." },
  { id: 17, type: "back", value: "<" },
  { id: 18, type: "number", value: "0" },
  { id: 19, type: "result", value: "=" },
];
